name: flutter_test_demo
description: "A new Flutter module project."

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_boost:
    git:
      url: 'https://github.com/alibaba/flutter_boost.git'
      ref: '4.6.5'
  provider: ^6.1.1

  dio: ^5.9.0
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.2.3
  shared_preferences: ^2.5.3
  json_annotation: ^4.8.0
  pull_to_refresh: ^2.0.0
  carousel_slider: ^5.1.1
  shimmer: ^3.0.0
  collection: ^1.18.0

  path_provider:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/path_provider/path_provider"

dependency_overrides:
  path_provider:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/path_provider/path_provider"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  module:
    androidX: true
    androidPackage: com.example.flutter_test_demo
    iosBundleIdentifier: com.example.flutterTestDemo
    ohosBundleName: com.example.flutter_test_demo
